### ISSUE TITLE
Här händer det inte mycket

### ISSUE THREAD

**Issue by k3larra** [MahApp/Pfi2Project15#1]
Jag hade förväntat mig att det börjar synas lite arbetsmaterial i form av konceptbeskrivningar användningsstudier.
Sharing is caring :) 

Detta är plattformen även för halvfärdiga saker, man kan radera, ändra influeras och lära.......
Lite om era tekniska studier etc, hur är ramverket problem fungerar det etc.

**Comment by AnderssonX** [comment]
Lars, vi håller på sammanställer lite av vår research i ett google docs-dokument. Rekommenderar du att vi exporterar det till en PDF och lägger upp på github? Skall vi i så fall skapa en mapp för det i projektet och pusha det? Eller hur rekommenderar du att vi gör?

**Comment by amandalundiusmorck** [comment]
Vi har sammanställningsmöte imorgon och lovar att dela med oss då.

Mvh
Amanda

--- Originalmeddelande ---

Från: "Lars Holmberg" <notifications@github.com>
Skickat: 10 mars 2015 14:41
Till: "MahApp/Pfi2Project15" <Pfi2Project15@noreply.github.com>
Kopia: "Amanda Lundius Mörck" <amandalundius@hotmail.com>
Ämne: Re: [Pfi2Project15] Här händer det inte mycket (#1)

Assigned #1 to @amandalundiusmorck.

---
Reply to this email directly or view it on GitHub:
https://github.com/MahApp/Pfi2Project15/issues/1#event-249307261

**Comment by k3larra** [comment]
Att ni formaterar det som markdown och skriver det direkt I Wikin:

Förmodligen kan man exportera från Gdocs till markdown.

bilderna kan ni antingen ha på nätet någonstans eller direkt uppladdade I projektet.

Mvh

/L

**Comment by k3larra** [comment]
Skriv allt som ni skapar I Wikin jag var kanske lite otydlig där.

Mvh

/L

**Comment by k3larra** [comment]
Like this…

http://lifehacker.com/this-script-converts-google-documents-to-markdown-for-e-511746113
