### ISSUE TITLE
Research på Kronox

### ISSUE THREAD

**Issue by jspr86** [MahApp/Pfi2Project15#11]
Utlagt på Marcus?

**Comment by Mcni91** [comment]
Skolor som använder kronox:

Ersta Sköndal högskola
Handelshögskolan i Stockholm
Högskolan i Borås
Högskolan i Gävle
Högskolan i Jönköping
Högskolan Kristianstad
Högskolan Väst
Konstfack
Mälardalens högskola
Malmö högskola
Örebro universitet
Sveriges Lantbruksuniversitet

Högskolan i Borås svarar för administrationen för konsortiet, samt drift och utveckling av programvaran.

**Comment by jspr86** [comment]
Avslutat
