### ISSUE TITLE
Klargör ansvarsområden för wiki + issues och github

### ISSUE THREAD

**Issue by jspr86** [MahApp/Pfi2Project15#14]

**Comment by ChristianBlom** [comment]
I vår grupp (AlexanderGruppen), så är jag Wiki+Issues ansvarig och Alexander är Github ansvarig

**Comment by AnderssonX** [comment]
Jag är Wiki-ansvarig i vår grupp, TeamMattias!

**Comment by AnderssonX** [comment]
Jag är Wiki-ansvarig och Alrik är Github ansvarig i vår grupp, TeamMattias!

**Comment by nellieostergaard** [comment]
Jag är Wiki- och issue ansvarig i gruppAmanda

**Comment by jspr86** [comment]
Ok, där finns en ny sida där ni kan skriva in medlemmar och ansvarsområden.
