### ISSUE TITLE
Gemensam grafisk profil

### ISSUE THREAD

**Issue by lstenstadvold** [MahApp/Pfi2Project15#16]
Vi behöver vara överens mellan grupperna om vissa grafiska aspekter; t ex ramar, typsnitt, bakgrundsfärg, textfärg, hierarki (rubriker och text), animationer (ticker-effekt, GIFar, övergångar). 

Det förslogs att varje grupp har en representant som ansvarar för den gemensamma grafiska profilen. Representanterna borde träffas så snart som möjligt så själva grupperna kan arbeta fram en wireframe för deras område.

**Comment by joHag90** [comment]
Vi skickar Freyja.

**Comment by lstenstadvold** [comment]
Det finns schemalagd tid på fredagseftermiddag att träffas och diskutera grafisk profil. Det kan vara rimligaste tiden att mötas. Förslaget är att vi gör wireframes i våra grupper först och sen bestämmer representanterna om ett utseende på fredagseftermiddag.

**Comment by Aliide** [comment]
Men skulle inte det vara bestämt till fredag? Skulle det inte vara skönt att typ ses imorgon så att man kan arbeta i grupperna på fredag?

**Comment by antonblomster** [comment]
Jag tycker att vi ses någon timme imorgon och börjar brainstorma för interfacet, efter lunch?

**Comment by axelbirgersson** [comment]
Låter bra

**Comment by JoakimWinsgard** [comment]
Efter lunch var?

**Comment by antonblomster** [comment]
kl 13 vid cafeterian?

**Comment by JoakimWinsgard** [comment]
Absolut, ses där.

**Comment by EmergencyBattle** [comment]
Uppmärksammat

**Comment by Aliide** [comment]
blir bra!

**Comment by AnderssonX** [comment]
Vi hade riktat in oss på Fredagen men Casandra från vår grupp kommer imorgon.

**Comment by Mannewe** [comment]
Finns nu en sida på wikin för grafisk profil, jag vet inte varför den inte kommer upp bland de andra sidorna men klickar man på "Pages" i wikin så finns den i listan där. Om någon vet hur man kan fixa detta får man gärna göra det
