### ISSUE TITLE
News & Dagens lunch

### ISSUE THREAD

**Issue by victoriakarlsson** [MahApp/Pfi2Project15#19]
Tänka på hur våra wireframes ska se ut, ( måste vänta och se hur den gemensamma grafiska profilen kommer bli). Vi måste även höra med de olika restauranger om de har någon specifiklista som fungerar att ladda ner och inte bara att varje restaurang skriver ut det som en text på sin hemsida. Vi måste även komma fram till exakt vilka nyheter vi ska ha med om vi ska välja ut 2-3 av de största seminarium/dag eller om vi ska ha en lista på alla seminarium.

**Comment by Rasmus1989** [comment]
Jag har kontaktat restaurangerna och frågat efter API eller någon slags data med planerad matsedel för terminen eller en tid framåt. Väntar på svar..

**Comment by victoriakarlsson** [comment]
De olika event som ska med ska på samma sätt som schemat uppdateras hela tiden. Vi kommer ha tre seminarium åt gången där de tre närmst liggande föreläsningar kommer visas på skärmen. Vi hade velat ha en fjärdedel av skärmen, och av den delen har vi tänkt att vi ska dela upp den i två där ena sidan har nyheter och den andra visar dagens lunch.

**Comment by Rasmus1989** [comment]
Har inte fått svar från någon av restaurangerna.. Jag ger dem några fler timmar annars kanske jag kan ringa eller gå dit och fråga

**Comment by k3larra** [comment]
De har inga API utan ni måste parsa deras HTML.

**Comment by Rasmus1989** [comment]
Vem ska man ta kontakt med om det Lars? Är det IT-service eller?


2015-03-12 12:23 GMT+01:00 Lars Holmberg <notifications@github.com>:

**Comment by Rasmus1989** [comment]
![wireframe1](https://cloud.githubusercontent.com/assets/10772681/6617373/56bc0300-c8b8-11e4-986e-385f0b48fe55.png)
![wireframe2](https://cloud.githubusercontent.com/assets/10772681/6617374/59acf7e0-c8b8-11e4-9206-d4a51311dc2b.png)

**Comment by k3larra** [comment]
Det gör man helt själv, du skriver ett program som läser HTML filen. Sen plockar du fram det som är relevant.

**Comment by Rasmus1989** [comment]
okok!

**Comment by Rasmus1989** [comment]
Restaurang Freda har svarat;
vi lägger menyn inför varje kommande veckan på torsdagen.
Den läggs oftast ut på vår hemsida efter fredag lunch
Vi kan lägga in informationen i er databas eller göra den tillgängligg inför varje menysläpp

**Comment by victoriakarlsson** [comment]
![11046655_10153185663612612_802877492578199183_n](https://cloud.githubusercontent.com/assets/10706927/6620273/1e22b8e6-c8d0-11e4-8f8e-4eb9c1f23c99.jpg)
![11046525_10153185663662612_6061807909099724558_n](https://cloud.githubusercontent.com/assets/10706927/6620296/409cd456-c8d0-11e4-9c8a-ded5e103f1db.jpg)
11058764_10153185663722612_77294854163966016_n

**Comment by victoriakarlsson** [comment]
Första två skisserna tänkte vi under lunchtid och eventuellt om vi får mer plats på eftermiddagen kan vi vi visa mer av de olika event som kommer under följande dag.

**Comment by Aliide** [comment]
![nyheterochinfo_wireframe](https://cloud.githubusercontent.com/assets/10706862/6636396/1782be1e-c970-11e4-8f99-fa2d2cf074e7.jpg)

**Comment by Aliide** [comment]
typ
