### ISSUE TITLE
Sammanställa researchen

### ISSUE THREAD

**Issue by jspr86** [MahApp/Pfi2Project15#2]
Vi borde kanske göra en enhetlig sammanställning av all research? Efter onsdag ifall någon av grupperna har sina wiki-sidor som hjälp till presentationen.

**Comment by k3larra** [comment]
Bra ide’ om det ligger på Wikisidorna i morgon kan göra en sammanställning senare. 

Vi behöver komma överens om en struktur på de sidorna. Jag känner inte till möjligheter och begränsningar där men vi kanske kan hitta en från varje grupp som kan utforska det samt agera redaktör för de sidorna under resten av veckan…..

**Comment by Brandstrom** [comment]
Skickar frågeformuläret här också just in case....

**Comment by jspr86** [comment]
Påbörjad

**Comment by jspr86** [comment]
Har sammanställt de första korta användarstudierna under [[Preliminär användarstudie]]. Endast de generella dragen och de gemensamma frågorna har tagits med. Kanske ska research för specifika moduler skrivas under respektive modul?
