### ISSUE TITLE
Research Kronoxgruppen, översta byggnaden som undersökts?

### ISSUE THREAD

**Issue by jspr86** [MahApp/Pfi2Project15#23]
Det behövs förtydligas vilken byggnad ni avser överst i er wiki page. Viktigt nu när all info ska sammanställas.

**Comment by AnderssonX** [comment]
All research som gjorts i en specifik byggnad står under respektive rubrik; Gäddan, Orkanen osv. 
Syftar du på enkäten? "Svar från enkätundersökning" ? Så är det en enkät som finns online som vem som helst kunnat svara på. Men de enda svaren som är redovisade där nu är från elever på Gäddan.

**Comment by AnderssonX** [comment]
All research som gjorts i en specifik byggnad står under respektive rubrik; Gäddan, Orkanen osv. 
Syftar du på enkäten? "Svar från enkätundersökning" ? Så är det en enkät som finns online som vem som helst kunnat svara på. Men de enda svaren som är redovisade där nu är från elever på Gäddan.

**Comment by jspr86** [comment]
Ok.
