### ISSUE TITLE
Klockgruppen, hur många tillfrågade personer?

### ISSUE THREAD

**Issue by jspr86** [MahApp/Pfi2Project15#25]
Har ni möjligtvis någon uppfattning om hur många ni frågat, var ni frågat dom etc? Utan denna infon är det svårt att sammanfoga era resultat med de andras.

**Comment by axelbirgersson** [comment]
Runt 10 personer var tillfrågade

**Comment by axelbirgersson** [comment]
Personerna blev tillfrågade på kranen

**Comment by jspr86** [comment]
Nice tack!
