### ISSUE TITLE
Val av API

### ISSUE THREAD

**Issue by RobbanM** [MahApp/Pfi2Project15#28]

**Comment by Therealnaxos** [comment]
Vi har valt att använda oss utav Skånetrafikens API.
Tillägger att taggarna, <Details> kombinerat med <Importance> innehåller nyckelinformation för vårt projekt.

**Comment by jspr86** [comment]
Är denna issuen avklarad? Vet alla vad som gäller? Om vi har valt API skriv det tydligt på vår modulsida

**Comment by RobbanM** [comment]
Jag lägger till!
