### ISSUE TITLE
Flytta in research om skånetrafiken och trafikverkets api in i korrekt modul.

### ISSUE THREAD

**Issue by jspr86** [MahApp/Pfi2Project15#30]
Researchen om dessa api'erna kanske står bättre i sidan för vår modul?

**Comment by Bankmongot** [comment]
Skall jag lägga in det som en separat wiki-sida eller som en del på "Trafikstörningar"-wikin?

**Comment by jspr86** [comment]
Tänkte att det kunde ligga som en del på trafikstörningar sidan?

**Comment by Bankmongot** [comment]
Absolut. Ordnar det.

**Comment by Bankmongot** [comment]
Har importerat texten från Skånetrafiken & Trafikverkets API-text in i Trafikstörningar-wikin. Skapat en ny sektion i texten som kallas Research. Tänkte vi kan fylla på där allt eftersom.

**Comment by Bankmongot** [comment]
Har också tagit bort sidan från menyn. All info ang. API:erna ligger nu under "Trafikstörningar".

**Comment by jspr86** [comment]
Rasmus, detta gällde grupp viktor. Öppna hellre en ny issue för grupp joel.
