### ISSUE TITLE
Prioriteringar av news & dagens lunch

### ISSUE THREAD

**Issue by victoriakarlsson** [MahApp/Pfi2Project15#31]
7-11 : låg prioritet, möjligtvis ha en liten del till att visa vilka event som startar
11-14 : hög prioritet, visning av dagens lunch och även vad som kommer hända under eftermiddagen
14-24 lägre prioritet men vid plats visa morgondagens event

**Comment by jspr86** [comment]
Skriv in det i tabellen i sidan "Moduler"

**Comment by joHag90** [comment]
Har nu skrivit in våra prio-önskningar. News och Lunch går under samma kategori numera.
