### ISSUE TITLE
Prioriteringar under dagen för Kronox

### ISSUE THREAD

**Issue by AnderssonX** [MahApp/Pfi2Project15#33]
Prioriterade timmar för kronoxmodulen
Vi har baserat våra prioriterade timmar på tider då det är flest schemalagda timmar. Låg prio under lunch och under sen eftermiddag + kväll & natt.

Hög prio: 08.30 - 11.00  
Låg prio: 11.00-12.45
Hög prio: 12.45-15.00
Låg prio: 15.00-08.30

**Comment by jspr86** [comment]
Skriv in det i tabellen i sidan "Moduler"

**Comment by AnderssonX** [comment]
Done!
