### ISSUE TITLE
Hjälp med HTML-parsing

### ISSUE THREAD

**Issue by emelie-larsson** [MahApp/Pfi2Project15#34]
Skriver redan nu att vi i Grupp Joel kommer behöva hjälp med html-parsing nästa vecka.

**Comment by k3larra** [comment]
Det finns ett exempel på hur man läser en HTML sida i de exempel jag hade på sista föreläsningen.
![här](https://github.com/MahApp/KD322B_public/blob/master/LectureExample/src/se/mah/k3/pfi2/lecture7/ReadAndWriteWithScanner.java)

När man sen har infon som strängar så letar man i dem efter taggar med Strängmetoder.
Prova själva så kommer jag och hjälper er sen.
mvh
/L

**Comment by emelie-larsson** [comment]
Vi har klarat av att skriva ut HTML-koden på de sidor vi behöver, men nu sitter vi fast med att skriva kod för att hitta rätt rader/tags som är relevanta för vår uppgift.

**Comment by k3larra** [comment]
Kan ni comitta upp det ni har så kan jag kommentera där,
Ange vilken branch åsså så jag vet.

**Comment by joHag90** [comment]
Ska vara committat genom branch GruppJoel nu

**Comment by k3larra** [comment]
Så nu finns det ett exempel. Kopierade er fil och ändrade samt kommenterade. Förvänta er inte att det skall gå att hitta en generell lösning utan det är bara hårt arbete som gäller.

**Comment by joHag90** [comment]
Tack, hade inte tänkt på att använda indexOf och substrings
