### ISSUE TITLE
Städning av wiki

### ISSUE THREAD

**Issue by AnderssonX** [MahApp/Pfi2Project15#37]
Vi pratade under wikimötet om att städa upp wikin. 
Bland annat genom att lyfta in de enskilda modulernas researchsidor som nu ligger under "research" till modulens egen sida under "moduler". Så kan vi hålla research-delen av wikin generell för sådant som berör hela projektet. Vi har dessutom en sida under research med en sammanställning av all redovisad research. Så kan vi radera de överflöda sidorna under research sedan. 

Jag har flyttat innehållet i kronoxgruppens research till schema under moduler och jag flyttade också innehållet från sidan "Prototype wireframe & suggestions" till schema samt GruppMannes sida "Klocka & väder" under moduler. Rekommendera att övriga grupper gör samma sak.

**Comment by jspr86** [comment]
Detta är fortfarande inte avklarat. Joels grupp och Mannes grupp, flytta in eran research till eran modulsida, eller ta bort sidan. Alternativt redigerar ni menyn så att era sidor inte står med.

**Comment by joHag90** [comment]
Har flyttat över vår research till vår modulsida nu och tagit bort de gamla research-sidorna.

**Comment by jspr86** [comment]
Avslutat
