### ISSUE TITLE
Futura Medium?

### ISSUE THREAD

**Issue by EmergencyBattle** [MahApp/Pfi2Project15#38]
In the font package for windows there is no font called Futura Medium, does it have another name or should we use a subsititute?

**Comment by jspr86** [comment]
Jag är osäker på om det va detta du menad.
https://www.dropbox.com/sh/9n04wthn9v058lk/AABZN2Jlc8eUExXZNfOr22nna?dl=0
Denna fonten (Futura Std, inkluderar även medium weight) är hämtad från Adobe Folio 11. Den grafiska gruppen bör kolla upp licenser om ni vill använda den.

**Comment by EmergencyBattle** [comment]
Tack, det funkade.

**Comment by JoakimWinsgard** [comment]
Bauer types innehar upphovsrätten till Futura Medium. 
Malmö Högskola använder Futura och med det så känns det ganska säkert att anta att MAH har licens för att använda fonten.
När det kommer till att använda fonten i en app så fungerar licenseringen så att man betalar en engångskostnad för varje revision av en app som publiceras. 
Eftersom att vårt program inte är tänkt att publiceras och användas i kommersiellt syfte är det tveksam om det är en desktop eller en app-licens som krävs.
MEN, med stöd av upphovsrättslagen (2 kap §11a) får vi lov att använda fonten i processen att ta fram vår prototyp. Först när den börjar visas för allmänheten måste licensavgift betalas.
Rimligtvis ligger den kostnaden på MAH ifall det skulle gå så långt att detta blir en realitet.
OBS: har man inte fonten via något program på sin dator så är man tekniskt sett skyldig att betala licens för sin egen dator om man vill ha den.
