### ISSUE TITLE
Utskrift av schema

### ISSUE THREAD

**Issue by undvictor** [MahApp/Pfi2Project15#44]
I dummypanel-klassen är det just nu ett table-objekt implementerat i kronoxfältet. Tänkte titta om jag får skrota den och implementera en canvas istället, då det blir lättare att göra det grafiska utifrån det.

**Comment by k3larra** [comment]
Absolut ni är helt fria att bygga er Kronox JPanel med vilken Layout ni vill. 
Det där är bara exempel och en JTable är kanske naturlig men lite fyrkantig dock kraftfull men kräver lite tid att tämja.........
