### ISSUE TITLE
Bussgruppens Wikisida

### ISSUE THREAD

**Issue by k3larra** [MahApp/Pfi2Project15#45]
Ni behöver rensa på er beskrivningsida där finns en massa information och ointressanta paj-diagram. Detta finns väl sammanfattat i användarstudien. 
Ni har även en massa olika designalternativ som visas och behöver rensa så att det syns vilket ni tänker implementera.
Titta på schema eller klocka och väder.

**Comment by ChristianBlom** [comment]
Ok Lars ska fixa ihop det.

**Comment by ChristianBlom** [comment]
Ta gärna en titt nu och se vad du tycker Lars, ska försöka hålla sidan kort, koncist men informativt hädanefter.

**Comment by k3larra** [comment]
Finemang :)
