### ISSUE TITLE
Funderingar gällande grafiska profilen och teckenstorlekar

### ISSUE THREAD

**Issue by AnderssonX** [MahApp/Pfi2Project15#50]
Jag tror vi måste uppdatera den grafiska profilen lite när det kommer till teckenstorlekar.
Det enda som står angivet är "Fonten vi använder oss av är Futura (book, medium, bold) 7 pt."

Vi måste naturligtvis bestämma detta mer utförligt med ex. separata storlekar för rubriker, brödtext, vissa undantag osv. Så att det blir någon form av symbios mellan modulerna och texterna som syns i dem. För tanken är väl ändå inte att allt skall vara i 7pt? Och 7pt blir väl dessutom sjukt svårt att läsa på en skärm med upplösningen 1080x1920? Vi använder ex. size 25 & 30 in the kronox module which is perfect for reading the screen from a few foot away.

Lars, tror du vi kan få tillgång till någon av de skärmar som faktiskt kommer användas? För vad jag har förstått så har grupperna fått testa på en gammal skärm som använder en mycket lägre upplösning än de andra skärmarna. De vanliga kör väl 1080? Den vid trappan i kranen som inte används kanske går att få tillgång till imorgon eller efter fredagen? Det skulle underlätta om vi kunde se hur det kommer se ut på de skärmar som skall användas.

**Comment by k3larra** [comment]
Jag har en HD TV som kan testa på skrev om det på WiKi. Säg bara till i morgon så kan jag sätta ut den vid sofforna jag är där vid 8 i morgon o har lite möte fram till 10.

On 19 Mar 2015 22:13, Mattias Andersson <notifications@github.com> wrote:

Jag tror vi måste uppdatera den grafiska profilen lite när det kommer till teckenstorlekar.
Det enda som står angivet är "Fonten vi använder oss av är Futura (book, medium, bold) 7 pt."

Vi måste naturligtvis bestämma detta mer utförligt med ex. separata storlekar för rubriker, brödtext, vissa undantag osv. Så att det blir någon form av symbios mellan modulerna och texterna som syns i dem. För tanken är väl ändå inte att allt skall vara i 7pt?

Och 7pt blir väl dessutom sjukt svårt att läsa på en skärm med upplösningen 1080x1920 ?

Lars, tror du vi kan få tillgång till någon av de skärmar som faktiskt kommer användas? För vad jag har förstått så har grupperna fått testa på en gammal skärm som använder en mycket lägre upplösning än de andra skärmarna. De vanliga kör väl 1080? Den vid trappan i kranen som inte används kanske går att få tillgång till imorgon eller efter fredagen? Det skulle underlätta om vi kunde se hur det kommer se ut på de skärmar som skall användas.

**Comment by axelbirgersson** [comment]
Problemet är att den skärmen du talar om inte är 1920x1080 utan 768x1024 vilket gör det svårt att testa en design som är anpassad för 1920x1080.

**Comment by k3larra** [comment]
Vilken skärm pratar jag om?

On 20 Mar 2015 06:58, axelbirgersson <notifications@github.com> wrote:

Problemet är att den skärmen du talar om inte är 1920x1080 utan 768x1024 vilket gör det svårt att testa en design som är anpassad för 1920x1080.

**Comment by axelbirgersson** [comment]
Skärmen vi i grafiska gruppen använde oss av i fredags som var placerad vid sofforna?

**Comment by k3larra** [comment]
Det finns många skärmar I denna världen ……

**Comment by undvictor** [comment]
Jag efterlyser ett regelverk kring Margins också, är det någon som vet något om det?
