### ISSUE TITLE
Möte

### ISSUE THREAD

**Issue by Rasmus1989** [MahApp/Pfi2Project15#55]
Vi i grupp Joel efterlyser ett möte med alla grupper så vi kan spika allas placering på skärmen samt bestämma vilka tider som skärmen ändras. 
Som jag förstod saken har grafiska gruppen inte spikat de frågorna än. 
Jag tror att senast idag måste alla grupper veta sina exakta mått så vi kan arbeta utifrån det.
Så om git-ansvariga, grafiska gruppen eller bara en person per grupp träffas efter lunch och bestämmer detta. 
Låter det rimligt?

**Comment by antonblomster** [comment]
Låter bra, utanför lärarrummet kl 13 då. Jag meddelar Grafiska gruppen!

**Comment by Rasmus1989** [comment]
Perfekt!

**Comment by Bankmongot** [comment]
Vart är "utanför lärarrummet" :)

**Comment by jspr86** [comment]
Avslutat antar jag.
