### ISSUE TITLE
Rensning i master

### ISSUE THREAD

**Issue by RobbanM** [MahApp/Pfi2Project15#71]
Skulle man behålla alla gamla java filer vi inte använder längre som ligger i mastern? Vi har sedan förra mergen sorterat allt i underpackages och rensat oanvända .java filer. Dock ligger alla dessa och skräpar i mastern. (traficinfo)

**Comment by k3larra** [comment]
Ja bra Ta bort allt av era gamla grejor ni inte använder i mastern.
